name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [master, "v*", "*.x"]
    paths-ignore: ["**.md"]

permissions:
  contents: read

jobs:
  ci:
    uses: sketch7/.github/.github/workflows/node-ci.yml@feature/promotable-app-release-cycle
